"""add stripe ids

Revision ID: c715fd30adc0
Revises: eaf8d39e8984
Create Date: 2025-10-14 08:18:28.540058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c715fd30adc0'
down_revision: Union[str, Sequence[str], None] = 'eaf8d39e8984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('stripe_checkout_id', sa.String(length=64), nullable=True))
    op.add_column('payments', sa.Column('stripe_payment_intent_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_payments_stripe_checkout_id'), 'payments', ['stripe_checkout_id'], unique=False)
    op.create_index(op.f('ix_payments_stripe_payment_intent_id'), 'payments', ['stripe_payment_intent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_stripe_payment_intent_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_stripe_checkout_id'), table_name='payments')
    op.drop_column('payments', 'stripe_payment_intent_id')
    op.drop_column('payments', 'stripe_checkout_id')
    # ### end Alembic commands ###
