"""add audit_events table

Revision ID: c8f0d4256966
Revises: 662d39c34da4
Create Date: 2025-11-04 09:41:32.022165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8f0d4256966'
down_revision: Union[str, Sequence[str], None] = '662d39c34da4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.drop_index(op.f('ix_admins_invited_by_id'), table_name='admins')
    op.create_index(op.f('ix_admins_status'), 'admins', ['status'], unique=False)
    op.drop_constraint(op.f('fk_admins_invited_by_id_admins'), 'admins', type_='foreignkey')
    op.create_foreign_key(None, 'admins', 'admins', ['invited_by_id'], ['id'])
    op.drop_index(op.f('ix_subs_stripe_subscription_id'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.create_index(op.f('ix_subs_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=False)
    op.drop_constraint(None, 'admins', type_='foreignkey')
    op.create_foreign_key(op.f('fk_admins_invited_by_id_admins'), 'admins', 'admins', ['invited_by_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_admins_status'), table_name='admins')
    op.create_index(op.f('ix_admins_invited_by_id'), 'admins', ['invited_by_id'], unique=False)
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
